apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ingress-traefik-depl.yml
  - echo-depl.yml
  - book-service-depl.yml
  - post-service-depl.yml
  - order-service-depl.yml
  - member-service-depl.yml
  - message-service-depl.yml